name: Website
on:
  push:
    branches:
    - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: "3.10"
    - name: Setup poetry
      uses: Gr1N/setup-poetry@v7
    - name: Run poetry
      run: poetry install
    - name: Run process script
      run: poetry run scripts.py process
    - name: Run mkdocs
      run: poetry run mkdocs build
    - name: Deploy website
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/develop' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "./site"
